/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Home.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Home.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <directionalLight intensity={0.7} decay={2} rotation={[-0.506, 0.629, 0.756]} />
        <OrthographicCamera makeDefault={false} far={100000} near={0} position={[-330.344, 650.541, 683.863]} rotation={[-0.76, -0.337, -0.304]} />
        <mesh geometry={nodes.Rectangle_5.geometry} material={nodes.Rectangle_5.material} position={[-718.402, 563.115, 107.753]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Rectangle_4.geometry} material={nodes.Rectangle_4.material} position={[-730.298, 1089.062, 182.99]} rotation={[Math.PI / 2, 0.099, -Math.PI / 2]} />
        <mesh geometry={nodes.Rectangle_3.geometry} material={nodes.Rectangle_3.material} position={[-717.181, 602.141, -402.632]} rotation={[0, 0, -Math.PI]} scale={[3.831, 1.496, 0.128]} />
        <mesh geometry={nodes.Rectangle_2.geometry} material={nodes.Rectangle_2.material} position={[677.647, 634.371, 202.674]} rotation={[0, -Math.PI / 2, 0]} scale={[-1.399, 1, 0.27]} />
        <mesh geometry={nodes.Rectangle.geometry} material={nodes.Rectangle.material} position={[-653.449, 0.326, 596.695]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Home.gltf')
