/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 house_v4.glb 
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { usePrevious } from '@uidotdev/usehooks';
import * as THREE from 'three';

export default function Model(props) {
	const { state } = props;
	const group = useRef();
	const { nodes, materials, animations } = useGLTF('/house_v4.glb');
	const { actions } = useAnimations(animations, group);
	const prev = usePrevious(state);

	useEffect(() => {
		if (state.isGarageOpen && !prev?.isGarageOpen) {
			//Open garage
			actions.CloseGarage.stop();
			actions.OpenGarage.reset();
			actions.OpenGarage.setLoop(THREE.LoopOnce);
			actions.OpenGarage.clampWhenFinished = true;
			actions.OpenGarage.play();
		} else if (!state.isGarageOpen && prev?.isGarageOpen) {
			//Close garage
			actions.OpenGarage.stop();
			actions.CloseGarage.reset();
			actions.CloseGarage.setLoop(THREE.LoopOnce);
			actions.CloseGarage.clampWhenFinished = true;
			actions.CloseGarage.play();
		}
	}, [state, actions.OpenGarage, actions.CloseGarage]);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				{/* LivingRoom Light */}

				{state.isLivingRoomLight ? (
					<pointLight
						color={new THREE.Color('white')}
						intensity={7}
						position={[0.5, 2, 0]}
					/>
				) : null}

				{/* BedRoom Light*/}
				{state.isBedRoomLight ? (
					<pointLight
						color={new THREE.Color('white')}
						intensity={1}
						position={[-0.8, 1.8, -2.2]}
					/>
				) : null}
				<group name="Node_0" scale={0.01}>
					<group name="Scene_1">
						<group
							name="Group"
							position={[-139, 59.135, -74.555]}
							rotation={[-1.638, 0, 0]}
							scale={[1.104, 1, 1]}
						>
							<mesh
								name="Rectangle_8"
								geometry={nodes.Rectangle_8.geometry}
								material={nodes.Rectangle_8.material}
								position={[10.056, -87.777, -33.164]}
								rotation={[-2.697, 0, Math.PI]}
								scale={[1.049, 1.013, 1]}
							/>
						</group>
						<group
							name="Default_Ambient_Light"
							position={[108.403, 213.841, -150.81]}
						/>
						<group
							name="Group_2"
							position={[191.105, 359.947, -193.649]}
							rotation={[0, 0, -1.215]}
							scale={[1, 1.04, 1]}
						>
							<mesh
								name="Rectangle_8001"
								geometry={nodes.Rectangle_8001.geometry}
								material={nodes.Rectangle_8001.material}
								position={[-11.044, -204.256, 0]}
								rotation={[Math.PI / 2, Math.PI / 2, 0]}
								scale={[1.02, 0.721, 1.225]}
							/>
						</group>
						<mesh
							name="Rectangle"
							geometry={nodes.Rectangle.geometry}
							material={nodes.Rectangle.material}
							position={[0, -109.918, -126.521]}
							rotation={[Math.PI / 2, 0, 0]}
							scale={[2.069, 2.039, 1.775]}
						/>
						<mesh
							name="Rectangle_2"
							geometry={nodes.Rectangle_2.geometry}
							material={nodes.Rectangle_2.material}
							position={[225.008, 134.412, -193.649]}
							rotation={[Math.PI / 2, Math.PI / 2, 0]}
							scale={[1.02, 0.721, 1.225]}
						/>
						<mesh
							name="Rectangle_3"
							geometry={nodes.Rectangle_3.geometry}
							material={nodes.Rectangle_3.material}
							position={[-20.061, 85.294, -193.649]}
							rotation={[Math.PI / 2, Math.PI / 2, 0]}
							scale={[1.22, 0.721, 1.225]}
						/>
						<mesh
							name="Rectangle_4"
							geometry={nodes.Rectangle_4.geometry}
							material={nodes.Rectangle_4.material}
							position={[-261.088, 45.799, -193.649]}
							rotation={[Math.PI / 2, Math.PI / 2, 0]}
							scale={[1.22, 0.721, 1.225]}
						/>
						<mesh
							name="Rectangle_5"
							geometry={nodes.Rectangle_5.geometry}
							material={nodes.Rectangle_5.material}
							position={[-8.015, 131.558, -314.35]}
							rotation={[0, 0, Math.PI / 2]}
							scale={[1.02, 2.022, 1.717]}
						/>
						<mesh
							name="Rectangle_6"
							geometry={nodes.Rectangle_6.geometry}
							material={nodes.Rectangle_6.material}
							position={[-137.071, 85.294, -193.649]}
							rotation={[Math.PI / 2, 0, 0]}
							scale={[1, 0.721, 1.495]}
						/>
						<mesh
							name="Rectangle_7"
							geometry={nodes.Rectangle_7.geometry}
							material={nodes.Rectangle_7.material}
							position={[107.998, 85.294, -193.649]}
							rotation={[Math.PI / 2, 0, 0]}
							scale={[1, 0.721, 1.495]}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/house_v4.glb');
